# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  database: dev_cms_5thparadigm
  username: seancarroll
  password: rana1234
  host: localhost
  encoding: UTF8 
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tst_cms_5thparadigm
  username: seancarroll
  password: rana1234
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: prd_cms_5thparadigm
  username: seancarroll
  password: rana1234
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000



